Added Visual Studio for Windows XAMLator extension
ylatuya/XAMLator pull request #53
Opened 2019-03-17 17:13 UTC by jsuarezruiz

Changes:
- Created basic version of the **extension** for Visual Studio for **Windows**. In future versions, we can improve many details (extend Output Window to show details about what is happening at every moment, create an options pane to enable or disable, etc.).
- Added **WPF** sample project.

_NOTE: In other PR will include UWP (require a new Server project with a UWP library too) and in other one will update some packages (Xamarin.Forms, etc). Initially I was going to add it here, but it would be a very complex PR to review._

2019-03-17 20:25 UTC, ylatuya requested changes
Everything looks good, the only thing I would like to understand a bit more before merging are the changes from shared projects to libraries.
The binary  XAMLator.Client.VisualStudio/Newtonsoft.Json.dll has been committed to the repo, I would prefer not having binaries in the history and rely on NuGet to install it.

2019-03-17 20:25 UTC, ylatuya commented on SampleApp/XAMLator.SampleApp/LabelView.xaml.cs
> +    public partial class LabelView : ContentView
It seems the indentation has been changed. I will check into exporting the current setting into an editorconfig file

2019-03-17 20:25 UTC, ylatuya commented on XAMLator.Client.Net461/XAMLator.Client.Net461.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
What's the reason to convert XAMLator.Client into a library instead of a shared project? Is this a requirement for the Visual Studio addin?

2019-03-17 20:25 UTC, ylatuya commented on XAMLator.Core.Net461/XAMLator.Core.Net461.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Same as for the XAMLator.Client, is there is a reason why this has to be converted into a library instead of shared project?

2019-03-18 18:47 UTC, jsuarezruiz commented
The .NET libraries is just for be able to use it from an VSIX project (Visual Studio for Windows extension).

2019-03-19 14:54 UTC, ylatuya commented
> The .NET libraries is just for be able to use it from an VSIX project (Visual Studio for Windows extension).

Can't the project  XAMLator.Client.VisualStudio/XAMLator.Client.VisualStudio.csproj include both XAMLator.Core and XAMLator.Client as shared projects instead? Is it a limitation in this kind of projects ?

2019-03-19 16:43 UTC, jsuarezruiz commented
Exactly that.

2019-03-24 15:50 UTC, IoTFier commented
Hi @ylatuya , @jsuarezruiz - any testing help that I could provide you in validating the CI build ?

2019-03-24 21:46 UTC, merged

2019-03-24 21:52 UTC, ylatuya commented
I will be integrating the windows builds in the CI pipelines in this PR https://github.com/ylatuya/XAMLator/pull/54